/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CsiMethod {
  src: string
  dst?: string
  operator?: boolean
}
export interface RewriterConfig {
  chainSourceMap?: boolean
  comments?: boolean
  localVarPrefix?: string
  csiMethods?: Array<CsiMethod>
  hardcodedSecret?: boolean
}
export interface ResultWithoutMetrics {
  content: string
  hardcodedSecretResult?: HardcodedSecretResult
}
export interface HardcodedSecretResult {
  file: string
  literals: Array<LiteralInfo>
}
export interface LiteralInfo {
  value: string
  ident?: string
  line?: number
}
export class Rewriter {
  constructor(config?: RewriterConfig | undefined | null)
  rewrite(code: string, file: string): ResultWithoutMetrics
  csiMethods(): Array<string>
}
