name: Build

on:
  workflow_dispatch:

  pull_request:
    branches:
    - main

jobs:
  build-native:
    strategy:
      matrix:
        target:
          - name: windows 64 bits
            os: windows-2019
            artifact: iast-rewriter.win32-x64-msvc
            
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          architecture: ${{ matrix.target.arch }}
      - run: npm ci --ignore-scripts
      - run: npm run buildAndTest:windows
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.artifact }}
          path: ${{ matrix.target.artifact }}.node
    
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - dockerfile: Dockerfile
            artifact: iast-rewriter.linux-x64-gnu
          - dockerfile: alpine.Dockerfile
            artifact: iast-rewriter.linux-x64-musl
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: docker build -t build -f ./docker/${{ matrix.target.dockerfile }} .
      - run: docker run --name builder build
      - run: docker cp builder:/build/${{ matrix.target.artifact }}.node .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.artifact }}
          path: ${{ matrix.target.artifact }}.node

  static-checks:
    strategy:
      matrix:
        run:
          - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run ${{ matrix.run }}
      
  all-good:
    needs:
      - build-docker
      - static-checks
      
    runs-on: ubuntu-latest
    steps:
      - run: echo '🚀🚀🚀🚀🚀'
