name: Build

on:
  workflow_dispatch:

  pull_request:
    branches:
    - main

jobs:
  build-native:
    strategy:
      matrix:
        target:
          - name: linux 64 bits
            buildid: linux
            os: ubuntu-latest
            artifact: iast-rewriter.linux-x64-gnu
          - name: windows 64 bits
            buildid: windows
            os: windows-latest
            artifact: iast-rewriter.win32-x64-msvc
          - name: macos 64 bits
            buildid: darwin
            os: macos-latest
            artifact: iast-rewriter.darwin-x64
                        
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci --ignore-scripts
      - run: npm run build:${{ matrix.target.buildid }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.artifact }}
          path: ${{ matrix.target.artifact }}.node
    
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - name: alpine 64 bits
            dockerfile: alpine.Dockerfile
            artifact: iast-rewriter.linux-x64-musl
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: docker build -t build -f ./docker/${{ matrix.target.dockerfile }} .
      - run: docker run --name builder build
      - run: docker cp builder:/build/${{ matrix.target.artifact }}.node .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.artifact }}
          path: ${{ matrix.target.artifact }}.node

  static-checks:
    strategy:
      matrix:
        run:
          - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run ${{ matrix.run }}

  pack:
    needs: ['build-native', 'build-docker']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - run: npm ci --ignore-scripts          
      - run: npm run artifacts
      - run: npm pack
      - run: npm pack npm/linux-x64-gnu/
      - run: npm pack npm/linux-x64-musl/
      - run: npm pack npm/win32-x64-msvc/
      - run: npm pack npm/darwin-x64/      
      - uses: actions/upload-artifact@v2
        with:
          name: datadog-native-iast-rewriter
          path: '*.tgz'

  test-native:
    needs: ['pack']
    strategy:
      matrix:
        target:
          - name: linux 64 bits
            os: ubuntu-latest
            artifact: linux-x64-gnu
          - name: windows 64 bits
            os: windows-latest
            artifact: win32-x64-msvc
          - name: macos 64 bits
            os: macos-latest
            artifact: darwin-x64

    runs-on: ${{ matrix.target.os }}
    env:
      NPM_REWRITER: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci --ignore-scripts
      - uses: gagle/package-version@v1
        id: package-version
      - uses: actions/download-artifact@v2
        with:
          name: datadog-native-iast-rewriter
      - run: npm i datadog-native-iast-rewriter-${{ steps.package-version.outputs.version }}.tgz
      - run: npm i datadog-native-iast-rewriter${{ matrix.target.artifact }}-${{ steps.package-version.outputs.version }}.tgz
      - run: npm t
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/junit.xml'
          check_name: junit test report ${{ matrix.target.name }}

  all-good:
    needs: ['static-checks', 'test-native']
    runs-on: ubuntu-latest
    steps:
      - run: echo '🚀🚀🚀🚀🚀'
