name: v8 testing

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - feature/iast-chapter-1
  pull_request:

jobs:
  compile-v8-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          workflow_conclusion: success
          name: datadog-native-iast-rewriter

      - run: docker build -t test -f ./docker/v8test.Dockerfile .
      - id: run-tests
        run: |
          result=docker run --name v8tester test
          echo "::set-output name=result::$result"
      - name: Get the test results
        run: echo "${{ steps.run-tests.outputs.result }}"
