name: v8 testing

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - feature/iast-chapter-1
  pull_request:

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          workflow_conclusion: success
          name: datadog-native-iast-rewriter

      - run: docker build -t test -f ./docker/v8test.Dockerfile .
      - run: docker run --name v8tester test
