name: v8 testing

env:
  V8_BRANCH: 10.7.190

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - feature/iast-chapter-1
  pull_request:

jobs:
  compile-v8-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          workflow_conclusion: success
          name: datadog-native-iast-rewriter

      - name: Restore v8 builder Image
        id: cache-docker-v8
        uses: actions/cache@v3
        with:
          path: ci/cache/docker/v8builder
          key: cache-docker-v8builder

      - name: Update v8 builder Image Cache if cache miss
        if: steps.cache-docker-v8.outputs.cache-hit != 'true'
        run: docker build -t v8builder:$V8_BRANCH -f ./docker/v8test-builder.Dockerfile . && mkdir -p ci/cache/docker/v8builder && docker image save v8builder:$V8_BRANCH --output ./ci/cache/docker/v8builder/v8builder-$V8_BRANCH.tar

      - name: Use v8 builder Image Cache if cache hit
        if: steps.cache-docker-v8.outputs.cache-hit == 'true'
        run: docker image load --input ./ci/cache/docker/v8builder/v8builder-$V8_BRANCH.tar

      - name: Rewrite and run v8 tests
        id: run-tests
        run: docker build -t v8tester:$V8_BRANCH --build-arg V8_BRANCH=$V8_BRANCH -f v8test.Dockerfile . && docker run --name v8tester v8tester:$V8_BRANCH
